[test_config]
# Name of the project.
name = "structures"

# Include both line and branch coverage.
line-coverage = true
branch-coverage = true

# Specify the engine to use for collecting coverage.
engine = "Llvm"

# Include test functions in the coverage statistics.
include-tests = false

# Files to skip from testing.
exclude-files = ["benches/*"]

# Final coverage report to generate.
[report]
out = ["Html", "Lcov"]
