name: Rust

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check Rust version
        run: cargo --version

      - name: Deny cargo fmt warnings
        run: cargo fmt --check

      - name: Deny cargo clippy warnings
        run: cargo clippy -- --deny warnings --no-deps

      - name: Build crate
        run: |
          cargo build

      - name: Test coverage reporting
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo install cargo-tarpaulin
          time cargo tarpaulin

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: tarpaulin-report.html
